runtime: go123
instance_class: F1
entrypoint: sh -c "export GIN_MODE=$(gcloud secrets versions access latest --secret=GIN_MODE) && ./main"

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_instances: 10

inbound_services:
  - warmup
