steps:
  - name: "golang:1.23"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        go mod tidy
        go build -o main .

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --quiet",
      ]

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s"
